In [1]:
import os
os.chdir('..')

In [2]:
import pandas as pd
from sqlalchemy import create_engine
import sqlite3
import numpy as np
import matplotlib.pyplot as plt

from src.data_exploration.data_exploration import *

In [3]:
df = read_sqlite_table('housedata', './data/processed/rome_house_processing.db')

In [4]:
df

,latitude,longitude,price,buildingYear,surface,rooms,bathrooms,floor,floors,garage,luxury,features,Appartamento,Attico - Mansarda,Villa,Palazzo - Edificio,Villetta a schiera,Rustico - Casale,Casa indipendente,Loft
0,41.845798,12.545600,96000.0,1955,114,3,1,-1.0,3,0,0,"terrazza, cantina, Infissi esterni in doppio v...",1,0,0,0,0,0,0,0
1,41.845501,12.489500,500000.0,1971,122,4,2,4.0,6,1,0,"cancello elettrico, Fibra ottica, videoCitofon...",1,0,0,0,0,0,0,0
2,41.843842,12.489600,430000.0,1971,110,3,2,1.0,4,1,0,"Cucina, balcone, terrazza, Solo Cucina Arredat...",1,0,0,0,0,0,0,0
3,41.848701,12.487170,359000.0,1960,118,3,1,5.0,8,0,0,"Impianto di allarme, Cucina, balcone, Giardino...",1,0,0,0,0,0,0,0
4,41.841084,12.498786,625000.0,2021,126,4,2,5.5,6,1,0,"Cucina, balcone, terrazza, Infissi esterni in ...",0,1,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15334,41.879700,12.481500,880000.0,1960,150,5,2,1.0,4,0,1,"Idromassaggio, Caminetto, Fibra ottica, videoC...",1,0,0,0,0,0,0,0
15335,41.880199,12.483200,1950000.0,1960,135,4,3,5.0,5,1,1,"Porta blindata, balcone, terrazza, portiere in...",0,1,0,0,0,0,0,0
15336,41.880199,12.483200,550000.0,1960,60,2,1,2.0,5,0,1,"Porta blindata, terrazza, portiere intera gior...",1,0,0,0,0,0,0,0
15337,41.877300,12.481300,690000.0,1930,110,3,1,1.0,3,0,1,Esposizione doppia,1,0,0,0,0,0,0,0
15338,41.876060,12.486550,550000.0,1967,80,3,2,0.5,1,0,1,"Cucina, Parzialmente Arredato, Giardino privat...",0,0,0,0,0,0,1,0

In [5]:
parole = []
for i in range(len(df)):
    parole.append(df.loc[i,'features'])

In [6]:
parole_1 = []
for elem in parole:
    parole_1.append(elem.split(" "))

In [9]:
parole = []
for l in parole_1:
    for parola in l:
        parole.append(parola)

In [10]:
parole = list(set(parole))
parole

['allarme,',
 'terrazza,',
 'metallo',
 'muro,',
 'Cucina,',
 'Infissi',
 'esterni',
 'Reception,',
 'comune',
 'blindata,',
 'nord,',
 'Parzialmente',
 '4',
 'balcone,',
 'a',
 'muro',
 'cantina,',
 'Arredato,',
 'Idromassaggio',
 'carrabile,',
 '15',
 'Arredato',
 'Solo',
 'Fibra',
 'Taverna,',
 'allarme',
 'Porta',
 'Mansarda,',
 'cantina',
 'est,',
 '6',
 'sud',
 'Passo',
 'est',
 'videoCitofono',
 'PVC',
 'videoCitofono,',
 'balcone',
 'legno',
 '2',
 'satellitare,',
 'esterna,',
 '1',
 'Taverna',
 'comune,',
 '12',
 'Caminetto',
 'fumaria,',
 'canna',
 'Impianto',
 'privato,',
 'ovest',
 'intera',
 'interna,',
 '50',
 '3',
 'mezza',
 'blindata',
 'Reception',
 'parabola',
 'balconi',
 'singolo',
 'centralizzato,',
 'vetro',
 'cancello',
 'Armadio',
 'Esposizione',
 'doppia',
 '80',
 'esterna',
 'privato',
 'Cucina',
 'piscina,',
 'terrazza',
 'doppio',
 'legno,',
 '/',
 'e',
 'giornata,',
 'singolo,',
 'di',
 'Caminetto,',
 'tv',
 'nord',
 'Arredata',
 'elettrico,',
 'metallo,',
 'esposizione',
 'PVC,',
 'interna',
 'ottica,',
 'balconi,',
 'piscina',
 '10',
 'impianto',
 'giornata',
 'portiere',
 '5',
 'sud,',
 'triplo',
 'Giardino',
 'centralizzato',
 'Idromassaggio,',
 'con',
 'in',
 'Arredata,']

In [11]:
parole = [x.lower() for x in parole]

In [12]:
parole = list(set(parole))

In [13]:
parole = [x.strip(',') for x in parole]

In [14]:
parole = list(set(parole))

In [15]:
parole

['e',
 'arredata',
 'metallo',
 'arredato',
 'canna',
 'passo',
 'ovest',
 'portiere',
 'di',
 'tv',
 'satellitare',
 'intera',
 '50',
 'nord',
 '3',
 'ottica',
 'taverna',
 'esterni',
 'mezza',
 'blindata',
 'porta',
 'allarme',
 'esposizione',
 'interna',
 'parabola',
 'balconi',
 'singolo',
 'comune',
 'cantina',
 'armadio',
 'giardino',
 'vetro',
 'solo',
 'mansarda',
 '6',
 'infissi',
 'piscina',
 '10',
 'sud',
 'reception',
 'caminetto',
 'cancello',
 'giornata',
 'impianto',
 'doppia',
 '80',
 '4',
 'est',
 'esterna',
 'privato',
 'a',
 'parzialmente',
 '/',
 '5',
 'muro',
 'balcone',
 'triplo',
 'pvc',
 'legno',
 '2',
 'idromassaggio',
 'cucina',
 '1',
 'centralizzato',
 'terrazza',
 'carrabile',
 'elettrico',
 'fumaria',
 '15',
 'videocitofono',
 'doppio',
 'fibra',
 'con',
 'in',
 '12']

In [16]:
parole = ['balcone', 'terrazza', 'cantina', 'piscina', 'giardino']

In [17]:
for parola in parole:
    df[parola] = 0

In [18]:
df['features'] = df['features'].str.lower()
df['features']

0        terrazza, cantina, infissi esterni in doppio v...
1        cancello elettrico, fibra ottica, videocitofon...
2        cucina, balcone, terrazza, solo cucina arredat...
3        impianto di allarme, cucina, balcone, giardino...
4        cucina, balcone, terrazza, infissi esterni in ...
                               ...
15334    idromassaggio, caminetto, fibra ottica, videoc...
15335    porta blindata, balcone, terrazza, portiere in...
15336    porta blindata, terrazza, portiere intera gior...
15337                                   esposizione doppia
15338    cucina, parzialmente arredato, giardino privat...
Name: features, Length: 15339, dtype: object

In [19]:
for parola in parole:
    if parola == 'balcone':
        df.loc[(df['features'].str.contains(parola)) | df['features'].str.contains('balconi'), parola] = 1
    else:
         df.loc[(df['features'].str.contains(parola)), parola] = 1

In [21]:
df

,latitude,longitude,price,buildingYear,surface,rooms,bathrooms,floor,floors,garage,...,Palazzo - Edificio,Villetta a schiera,Rustico - Casale,Casa indipendente,Loft,balcone,terrazza,cantina,piscina,giardino
0,41.845798,12.545600,96000.0,1955,114,3,1,-1.0,3,0,...,0,0,0,0,0,0,1,1,0,0
1,41.845501,12.489500,500000.0,1971,122,4,2,4.0,6,1,...,0,0,0,0,0,1,1,1,0,1
2,41.843842,12.489600,430000.0,1971,110,3,2,1.0,4,1,...,0,0,0,0,0,1,1,0,0,0
3,41.848701,12.487170,359000.0,1960,118,3,1,5.0,8,0,...,0,0,0,0,0,1,0,0,0,1
4,41.841084,12.498786,625000.0,2021,126,4,2,5.5,6,1,...,0,0,0,0,0,1,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15334,41.879700,12.481500,880000.0,1960,150,5,2,1.0,4,0,...,0,0,0,0,0,1,1,1,0,1
15335,41.880199,12.483200,1950000.0,1960,135,4,3,5.0,5,1,...,0,0,0,0,0,1,1,0,0,1
15336,41.880199,12.483200,550000.0,1960,60,2,1,2.0,5,0,...,0,0,0,0,0,0,1,0,0,1
15337,41.877300,12.481300,690000.0,1930,110,3,1,1.0,3,0,...,0,0,0,0,0,0,0,0,0,0
15338,41.876060,12.486550,550000.0,1967,80,3,2,0.5,1,0,...,0,0,0,1,0,0,0,0,0,1

In [22]:
df = df.drop('features', axis=1)

In [23]:
save_to_sql('./data/processed/rome_house_cleaned.db', df, 'housedata')

In [24]:
df

,latitude,longitude,price,buildingYear,surface,rooms,bathrooms,floor,floors,garage,...,Palazzo - Edificio,Villetta a schiera,Rustico - Casale,Casa indipendente,Loft,balcone,terrazza,cantina,piscina,giardino
0,41.845798,12.545600,96000.0,1955,114,3,1,-1.0,3,0,...,0,0,0,0,0,0,1,1,0,0
1,41.845501,12.489500,500000.0,1971,122,4,2,4.0,6,1,...,0,0,0,0,0,1,1,1,0,1
2,41.843842,12.489600,430000.0,1971,110,3,2,1.0,4,1,...,0,0,0,0,0,1,1,0,0,0
3,41.848701,12.487170,359000.0,1960,118,3,1,5.0,8,0,...,0,0,0,0,0,1,0,0,0,1
4,41.841084,12.498786,625000.0,2021,126,4,2,5.5,6,1,...,0,0,0,0,0,1,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15334,41.879700,12.481500,880000.0,1960,150,5,2,1.0,4,0,...,0,0,0,0,0,1,1,1,0,1
15335,41.880199,12.483200,1950000.0,1960,135,4,3,5.0,5,1,...,0,0,0,0,0,1,1,0,0,1
15336,41.880199,12.483200,550000.0,1960,60,2,1,2.0,5,0,...,0,0,0,0,0,0,1,0,0,1
15337,41.877300,12.481300,690000.0,1930,110,3,1,1.0,3,0,...,0,0,0,0,0,0,0,0,0,0
15338,41.876060,12.486550,550000.0,1967,80,3,2,0.5,1,0,...,0,0,0,1,0,0,0,0,0,1